# Generated by Django 4.2.6 on 2023-10-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='ads/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verif', models.BooleanField()),
                ('date', models.DateField()),
                ('phone', models.TextField()),
                ('link', models.TextField()),
                ('response', models.PositiveSmallIntegerField(choices=[(0, 'моментально'), (1, 'за 5 минут'), (2, 'за пол часа'), (3, 'окола часа'), (4, 'в течении дня')], default=4, verbose_name='status')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
            ],
        ),
    ]
