# Generated by Django 4.2.6 on 2023-10-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='response',
            field=models.CharField(choices=[(0, 'моментально'), (1, 'за 5 минут'), (2, 'за пол часа'), (3, 'окола часа'), (4, 'в течении дня')], default='в течении дня', max_length=30),
        ),
    ]
