# Generated by Django 4.2.6 on 2023-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_person_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='response',
            field=models.CharField(choices=[('моментально', 'моментально'), ('за 5 минут', 'за 5 минут'), ('за пол часа', 'за пол часа'), ('окола часа', 'окола часа'), ('в течении дня', 'в течении дня')], default='в течении дня', max_length=30),
        ),
    ]
